version: "3.8"

services: 
  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
    volumes:
      - db-data:/var/lib/mysql
    expose:
      - 3306

  web:
    build: .
    ports:
      - "5000:80"
    volumes:
      - .:/code
      - ./config/nginx:/etc/nginx
  
volumes:
  db-data:
