version: "3.8"

services: 
  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
    volumes:
      - db-data:/var/lib/mysql
    expose:
      - 3306
    working_dir: /code
    command: bash ./recreate.sh

  web:
    # image: nginx
    build: .
    ports:
      - "5000:80"
    volumes:
      - .:/code
      - ./config/nginx:/etc/nginx
    # environment:
    #   - NGINX_HOST=whatever
    #   - NGINX_PORT=80
    # working_dir: /code
    # command: sh -c "
    #   apt update -y && 
    #   apt install -y ruby bundler git vim php && 
    #   bundle install &&
    #   nginx -g 'daemon off;' "

volumes:
  db-data:
