version: "3.8"

services: 
  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
    volumes:
      - db-data:/var/lib/mysql
    expose:
      - 3306

  web:
    image: nginx
    # build: .
    ports:
      - "5000:80"
    volumes:
      - ../../config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../../config/nginx/sites-available:/etc/nginx/sites-available
      - ../../config/nginx/conf.d:/etc/nginx/conf.d
    # links:
    #   - php
    # environment:
    #   - NGINX_HOST=whatever
    #   - NGINX_PORT=80
    # working_dir: /code
    # command: sh -c "
    #   apt update -y && 
    #   apt install -y ruby bundler git vim php && 
    #   bundle install &&
    #   nginx -g 'daemon off;' "

  php:
    # image: php:7.3-fpm
    build: .
      # context: ../..
      # dockerfile: config/docker/Dockerfile
    tty: true # keeps container running
    expose:
      - 9000
    volumes:
      - ../..:/code

volumes:
  db-data:
